---
- name: "Install Node_Exporter"
  notify: "Enable and start Node_Exporter"
  block:
    - name: "Create the node_exporter user"
      ansible.builtin.user:
        name: "{{ install_node_exporter_user }}"
        groups: "{{ install_node_exporter_group }}"
        append: true
        system: true
        create_home: false

    - name: "Install package from Github"
      block:
        - name: "Create lib path"
          ansible.builtin.file:
            path: "{{ install_node_exporter_lib_path }}"
            state: directory
            recurse: yes
            mode: "0700"
            group: "{{ install_node_exporter_group }}"
            owner: "{{ install_node_exporter_user }}"

        - name: "Download node_exporter binary to local folder"
          ansible.builtin.unarchive:
            src: "https://github.com/prometheus/node_exporter/releases/download/v{{ install_node_exporter_version }}/node_exporter-{{ install_node_exporter_version }}.linux-{{ install_node_exporter_architecture }}.tar.gz"
            dest: "{{ install_node_exporter_lib_path }}"
            mode: "0700"
            group: "{{ install_node_exporter_group }}"
            owner: "{{ install_node_exporter_user }}"
            remote_src: true

        - name: "Create a sym link to the bin"
          ansible.builtin.file:
            src: "{{ install_node_exporter_lib_path }}/node_exporter-{{ install_node_exporter_version }}.linux-{{ install_node_exporter_architecture }}/node_exporter"
            dest: "/usr/bin/node_exporter"
            state: link
            mode: "0700"
            group: "{{ install_node_exporter_group }}"
            owner: "{{ install_node_exporter_user }}"

    - name: "Import Node_Exporter service file"
      ansible.builtin.template:
        src: "templates/node_exporter.service.j2"
        dest: "/etc/systemd/system/node_exporter.service"
        mode: "0700"
        group: "root"
        owner: "root"
        lstrip_blocks: yes

- name: "Configure Node_Exporter"
  notify: "Restart Node_Exporter"
  block:
    - name: "Import Node_Exporter web configuration file"
      when: (install_node_exporter_ssl | default(false)) or (install_node_exporter_basic_auth | default(false))
      ansible.builtin.template:
        src: "templates/web-config.yml.j2"
        dest: "{{ install_node_exporter_web_config_file }}"
        mode: "0700"
        group: "{{ install_node_exporter_group }}"
        owner: "{{ install_node_exporter_user }}"
        lstrip_blocks: yes

    - name: "Apply permissions on Node_Exporter scrapes dir"
      ansible.builtin.file:
        path: "{{ install_node_exporter_install_path }}"
        state: directory
        recurse: yes
        group: "{{ install_node_exporter_group }}"
        owner: "{{ install_node_exporter_user }}"
        mode: "0700"
