---
- name: "Enable and start Node_Exporter"
  register: install_node_exporter__service_status
  changed_when: install_node_exporter__service_status.state != "restarted"
  ansible.builtin.service:
    name: "node_exporter"
    state: "started"
    enabled: yes

- name: "Restart Node_Exporter"
  register: install_node_exporter__service_status
  changed_when: install_node_exporter__service_status.state != "restarted"
  ansible.builtin.service:
    name: "node_exporter"
    state: "restarted"
    daemon_reload: true
