---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_node_exporter"
      tags:
        - "labocbz.install_node_exporter"
      vars:
        install_node_exporter_install_path: "{{ inv_install_node_exporter_install_path }}"
        install_node_exporter_lib_path: "{{ inv_install_node_exporter_lib_path }}"
        install_node_exporter_web_ssl_path: "{{ inv_install_node_exporter_web_ssl_path }}"
        install_node_exporter_web_config_file: "{{ inv_install_node_exporter_web_config_file }}"
        install_node_exporter_loglevel: "{{ inv_install_node_exporter_loglevel }}"
        install_node_exporter_version: "{{ inv_install_node_exporter_version }}"
        install_node_exporter_architecture: "{{ inv_install_node_exporter_architecture }}"
        install_node_exporter_ssl: "{{ inv_install_node_exporter_ssl }}"
        install_node_exporter_ssl_key: "{{ inv_install_node_exporter_ssl_key }}"
        install_node_exporter_port: "{{ inv_install_node_exporter_port }}"
        install_node_exporter_stats_exports: "{{ inv_install_node_exporter_stats_exports }}"
        install_node_exporter_basic_auth: "{{ inv_install_node_exporter_basic_auth }}"
        install_node_exporter_basic_auth_login: "{{ inv_install_node_exporter_basic_auth_login }}"
        install_node_exporter_basic_auth_password_hash: "{{ inv_install_node_exporter_basic_auth_password_hash }}"
      ansible.builtin.include_role:
        name: "labocbz.install_node_exporter"
